/**
 * Plugin Architecture Types
 *
 * The plugin system provides a modular way to handle the decompilation pipeline.
 */
import type { ClaudeRunnerResult } from '~/plugins/claude-runner/claude-runner-plugin.js';
import type { CompilerResult } from '~/plugins/compiler/compiler-plugin.js';
import type { ObjdiffResult } from '~/plugins/objdiff/objdiff-plugin.js';

import type { PipelineConfig } from './config.js';

/**
 * Mapping of plugin IDs to their result types
 */
export type PluginResultMap = {
  'claude-runner': PluginResult<ClaudeRunnerResult>;
  compiler: PluginResult<CompilerResult>;
  objdiff: PluginResult<ObjdiffResult>;
};

/**
 * Result status for a plugin execution
 */
export type PluginStatus = 'success' | 'failure' | 'skipped';

/**
 * Base result interface for all plugins
 */
export interface PluginResult<TPluginResult> {
  /** Unique identifier for the plugin that produced this result */
  pluginId: string;
  /** Human-readable plugin name */
  pluginName: string;
  /** Status of the execution */
  status: PluginStatus;
  /** Duration of execution in milliseconds */
  durationMs: number;
  /** Error message if status is 'failure' */
  error?: string;
  /** Human-readable output/logs from the plugin */
  output?: string;
  /** Any additional data specific to the plugin */
  data?: TPluginResult;
  /** Report sections generated by the plugin */
  sections?: PluginReportSection[];
}

/**
 * Context passed between plugins in the pipeline
 */
export interface PipelineContext {
  /** The current prompt being processed */
  promptPath?: string;
  /** Content of the prompt */
  promptContent?: string;
  /** Name of the function being decompiled */
  functionName: string;
  /** Generated C code from Claude */
  generatedCode?: string;
  /** Path to the compiled object file */
  compiledObjectPath?: string;
  /** Path to the target object file for comparison */
  targetObjectPath?: string;
  /** Current attempt number (1-indexed) */
  attemptNumber: number;
  /** Maximum retries allowed */
  maxRetries: number;
  /** Previous attempt results for feedback - maps plugin IDs to their results for each attempt */
  previousAttempts?: Array<Partial<PluginResultMap>>;
  /** Configuration options */
  config: PipelineConfig;
}

/**
 * Tool use content block in a chat message
 */
export interface ToolUseBlock {
  type: 'tool_use';
  id: string;
  name: string;
  input: Record<string, unknown>;
}

/**
 * Tool result content block in a chat message
 */
export interface ToolResultBlock {
  type: 'tool_result';
  tool_use_id: string;
  content: string;
}

/**
 * Text content block in a chat message
 */
export interface TextBlock {
  type: 'text';
  text: string;
}

/**
 * Content block that can appear in chat messages
 */
export type ContentBlock = TextBlock | ToolUseBlock | ToolResultBlock;

/**
 * Chat message in a conversation
 */
export interface ChatMessage {
  role: 'user' | 'assistant';
  content: string | ContentBlock[];
}

/**
 * Report data that a plugin can contribute to the benchmark report
 */
export type PluginReportSection =
  | {
      type: 'code';
      title: string;
      language: 'c' | 'markdown' | 'json' | 'text' | 'diff';
      code: string;
    }
  | {
      type: 'message';
      title: string;
      message: string;
    }
  | {
      type: 'chat';
      title: string;
      messages: ChatMessage[];
    };

/**
 * Plugin interface that all plugins must implement
 */
export interface Plugin<TPluginResult> {
  /** Unique identifier for this plugin */
  readonly id: string;
  /** Human-readable name */
  readonly name: string;
  /** Description of what this plugin does */
  readonly description: string;

  /**
   * Execute the plugin with the given context
   * @param context Current pipeline context
   * @returns Plugin result and optionally updated context
   */
  execute(context: PipelineContext): Promise<{
    result: PluginResult<TPluginResult>;
    context: PipelineContext;
  }>;

  /**
   * Called before retry to prepare context (e.g., add feedback)
   * @param context Current context
   * @param previousAttempts Results from previous attempts, mapping plugin IDs to their results.
   *                         If a plugin was skipped during an attempt, it will not have an entry.
   * @returns Updated context for retry
   */
  prepareRetry?(context: PipelineContext, previousAttempts: Array<Partial<PluginResultMap>>): PipelineContext;

  /**
   * Generate report sections for this plugin's execution
   * @param result The result from execution
   * @param context The pipeline context used during execution
   * @returns Array of report sections to display
   */
  getReportSections?(result: PluginResult<TPluginResult>, context: PipelineContext): PluginReportSection[];
}

/**
 * Result of running the full pipeline for a single prompt
 */
export interface PipelineRunResult {
  promptPath: string;
  functionName: string;
  success: boolean;
  attempts: AttemptResult[];
  totalDurationMs: number;
}

/**
 * Result of a single attempt through the pipeline
 */
export interface AttemptResult {
  attemptNumber: number;
  pluginResults: PluginResult<Record<string, unknown>>[];
  success: boolean;
  durationMs: number;
}

/**
 * Full pipeline results with plugin details
 */
export interface PipelineResults {
  timestamp: string;
  config: PipelineConfig;
  results: PipelineRunResult[];
  summary: {
    totalPrompts: number;
    successfulPrompts: number;
    successRate: number;
    avgAttempts: number;
    totalDurationMs: number;
  };
}
