/**
 * Report Generator Types
 *
 * Types for the benchmark report data structure.
 * These types are designed to be self-contained and independent from plugin implementations.
 */

/**
 * Tool use content block in a chat message
 */
export interface ReportToolUseBlock {
  type: 'tool_use';
  id: string;
  name: string;
  input: Record<string, unknown>;
}

/**
 * Tool result content block in a chat message
 */
export interface ReportToolResultBlock {
  type: 'tool_result';
  tool_use_id: string;
  content: string;
}

/**
 * Text content block in a chat message
 */
export interface ReportTextBlock {
  type: 'text';
  text: string;
}

/**
 * Content block that can appear in chat messages
 */
export type ReportContentBlock = ReportTextBlock | ReportToolUseBlock | ReportToolResultBlock;

/**
 * Chat message in a conversation
 */
export interface ReportChatMessage {
  role: 'user' | 'assistant';
  content: string | ReportContentBlock[];
}

/**
 * Report section that can be displayed for a plugin execution
 */
export type ReportSection =
  | {
      type: 'code';
      title: string;
      language: 'c' | 'markdown' | 'json' | 'text' | 'diff';
      code: string;
    }
  | {
      type: 'message';
      title: string;
      message: string;
    }
  | {
      type: 'chat';
      title: string;
      messages: ReportChatMessage[];
    };

/**
 * Plugin execution result for the report
 */
export interface ReportPluginResult {
  pluginId: string;
  pluginName: string;
  status: 'success' | 'failure' | 'skipped';
  durationMs: number;
  error?: string;
  output?: string;
  /** Plugin-specific data */
  data?: Record<string, unknown>;
  /** Report sections generated by the plugin */
  sections: ReportSection[];
}

/**
 * Single attempt result for the report
 */
export type ReportAttempt = {
  attemptNumber: number;
  success: boolean;
  durationMs: number;
  pluginResults: ReportPluginResult[];
};

/**
 * Result for a single prompt/function
 */
export interface ReportPromptResult {
  promptPath: string;
  functionName: string;
  success: boolean;
  attempts: ReportAttempt[];
  totalDurationMs: number;
  /** Result from programmatic-flow phase (e.g., m2c), if one was configured */
  programmaticFlow?: ReportAttempt;
}

/**
 * Summary statistics for the report
 */
export interface ReportSummary {
  totalPrompts: number;
  successfulPrompts: number;
  successRate: number;
  avgAttempts: number;
  totalDurationMs: number;
}

/**
 * Pipeline configuration for the report
 */
export interface ReportConfig {
  promptsDir: string;
  maxRetries: number;
  stallThreshold: number;
  claudeSystemPrompt: string;
  compilerFlags: string;
  target: string;
}

/**
 * Full benchmark report data
 */
export interface BenchmarkReport {
  version: number;
  timestamp: string;
  config: ReportConfig;
  results: ReportPromptResult[];
  summary: ReportSummary;
}

/**
 * Filter state for the report UI
 */
export interface ReportFilters {
  outcome: 'all' | 'success' | 'failure';
  failedAtPlugin?: string;
}

/**
 * Sort options for the report UI
 */
export interface ReportSort {
  field: 'name' | 'duration' | 'status';
  direction: 'asc' | 'desc';
}
